[package]
name = "in-memory-network"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
fastrand.workspace = true
parking_lot.workspace = true
pcap-file.workspace = true
pnet_packet.workspace = true
quinn.workspace = true
tokio.workspace = true

[dev-dependencies]
rcgen.workspace = true
