[package]
name = "in-memory-network"
version = "0.1.0"
edition = "2021"

[dependencies]
fastrand = { workspace = true }
pcap-file = { workspace = true }
pnet_packet = { workspace = true }
quinn = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
rcgen = { workspace = true }
