[package]
name = "in-memory-network"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
fastrand.workspace = true
futures-util = "0.3.31"
parking_lot.workspace = true
pcap-file.workspace = true
pnet_packet.workspace = true
quinn.workspace = true
tokio.workspace = true
uuid = { version = "1.11.0", features = ["v4"] }

[dev-dependencies]
bon = "3.3.0"
rcgen.workspace = true
