[workspace]
members = ["in-memory-network", "quinn-workbench"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.86"
fastrand = { version = "2.1.0" }
pcap-file = "2.0.0"
pnet_packet = "0.34.0"
quinn = "0.11"
quinn-proto = "0.11"
rcgen = "0.13.1"
rustls = { version = "0.23.8", default-features = false, features = ["ring"] }
tokio = { version = "1.37.0", features = ["test-util"] }

[patch.crates-io]
quinn = { git = "https://github.com/aochagavia/quinn.git", ref = "03fe410c1e482a488f2ce0f6f0a4a8e5cc7c041b" }
quinn-proto = { git = "https://github.com/aochagavia/quinn.git", ref = "03fe410c1e482a488f2ce0f6f0a4a8e5cc7c041b" }
